package com.lostin.auth.repository;

import com.lostin.auth.model.core.oauth_flow.CachedFlow;
import com.lostin.auth.model.core.oauth_flow.CachedFlowClient;

import java.util.Optional;
import java.util.UUID;

/*
    TODO:
     1) Delete flow after redirecting response back to browser
     2) Create another Redis repository to store AuthCode
     generated by server as a key and client credentials as value
 */

public interface OAuthFlowRepository {

    CachedFlow persistFlow(CachedFlowClient client);
    void saveFlow(CachedFlow flow);
    void deleteFlow(UUID flowId);
    Optional<CachedFlow> getCachedFlow(UUID flowId);
    boolean isFlowPresent(UUID flowId);
}
