package com.lostin.auth.repository;

import com.lostin.auth.model.core.oauth_flow.CachedFlow;
import com.lostin.auth.model.core.oauth_flow.CachedFlowClient;

import java.util.Optional;
import java.util.UUID;

/*
    TODO:
     1) Delete flow after redirecting response back to browser
     2) Create another Redis repository to store AuthCode
     generated by server as a key and client credentials as value
 */

public interface OAuthFlowRepository {

    CachedFlow persistFlow(CachedFlowClient client);
    void saveFlow(CachedFlow flow);
    void deleteFlow(UUID flowId);
    Optional<CachedFlow> getCachedFlow(UUID flowId);
    boolean isFlowPresent(UUID flowId);

    /** Repo for auth code
     *  Maybe in future it is a right option to take it out into another repository
     */
    void saveAuthCode(String code, UUID flowId);
    UUID getFlowIdByAuthCode(String code);

}
